# Generated by Django 4.1 on 2022-08-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawmania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeWinners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(null=True)),
                ('year', models.DateField(null=True)),
                ('prize', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
