# Generated by Django 4.1 on 2022-08-31 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawmania', '0003_prizewinners_digit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prizewinners',
            old_name='year',
            new_name='pub_date',
        ),
    ]
