# Generated by Django 4.1 on 2022-09-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawmania', '0004_rename_year_prizewinners_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
    ]
