# Generated by Django 4.1 on 2022-11-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawmania', '0006_alter_prizewinners_digit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prizewinners',
            name='digit',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='year',
        ),
    ]
