# Generated by Django 4.1 on 2022-11-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawmania', '0007_alter_prizewinners_digit_delete_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prizewinners',
            name='digit',
        ),
    ]
